export const TOGGLE_SEARCH_BAR = "TOGGLE_SEARCH_BAR";
export const FETCH_HOME_DATA = "FETCH_HOME_DATA";
export const OPEN_AUTH_MODAL = "OPEN_AUTH_MODAL";
export const USER_INFO = "USER_INFO";
export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_SINGLE_PAGE_DATA = "FETCH_SINGLE_PAGE_DATA";

export const REVIEW_PRODUCT_DATA = "REVIEW_PRODUCT_DATA";
export const REVIEW_SHOP_DATA = "REVIEW_SHOP_DATA";
export const FETCH_FAV_PRODUCTS = "FETCH_FAV_PRODUCTS";
export const HANDLE_IS_FAV = "HANDLE_IS_FAV";
export const CART_DATA = "CART_DATA";
export const HANDLE_ALERT_MODAL = "HANDLE_ALERT_MODAL";
export const HANDLE_NETWORK_ERROR = "HANDLE_NETWORK_ERROR";
export const HANDLE_CART_COUNT = "HANDLE_CART_COUNT";
export const HANDLE_CATEGORY_DATA = "HANDLE_CATEGORY_DATA";
export const HANDLE_CART_PAGE_COUNT = "HANDLE_CART_PAGE_COUNT";

export const HANDLE_FETCH_PRODUCT_CATEGORY_NOT_ON_SALE = "HANDLE_FETCH_PRODUCT_CATEGORY_NOT_ON_SALE";


export const HANDLE_ISLOADING = "HANDLE_ISLOADING"
export const HANDLE_UPDATE_PERSONALIZATION_CART_TEXT = "HANDLE_UPDATE_PERSONALIZATION_CART_TEXT"



export const URL = "http://localhost:5002";
